name: GazeBST_Pytorch_1-13
channels:
  - conda-forge
dependencies:
  - matplotlib-inline==0.1.6
  - py-opencv==4.6.0
  - numpy==1.23.5
  - python==3.10.8
  - ffmpeg==5.1.2
  - pillow==9.2.0
  - jupyter_client==7.4.8
  - ipython==8.7.0
  - openssl==3.0.7
  - matplotlib==3.6.2
  - pyzmq==24.0.1=py310hc407298_1
  - libtiff==4.4.0
  - decorator
  - libopencv==4.6.0
  - ipykernel==6.19.2
  - opencv==4.6.0